title: Aerostat Playlist Toolkit
description: Minimalistic Spotify Playlist aggregator for Aerostat podcasts
baseurl: "/aerostat"
url: "https://paulbaumer.github.io"
collections:
  episodes:
    output: true
    permalink: /episodes/:path/

defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
